language: csharp
os:
  - linux
sudo: required
dist: trusty
addons:
 apt:
  packages:
   - gettext
   - libcurl4-openssl-dev
   - libicu-dev
   - libssl-dev
   - libunwind8
   - zlib1g
dotnet: 1.0.1
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=true
# git update-index --chmod=+x build.sh
script:
  - ./build.sh